"""加载验证集选出的最佳模型，并在独立测试集上进行最终评估。

正确实验顺序：
1. compare_models.py 使用训练集训练候选模型；
2. compare_models.py 使用验证集比较并选择最佳模型；
3. 本脚本只在模型确定后使用测试集进行一次最终评估。
"""

# 允许在 Python 3.10 中使用现代类型注解。
from __future__ import annotations

# 导入 argparse，用于接收模型路径和随机种子参数。
import argparse

# 导入 Path，用于处理文件路径。
from pathlib import Path

# 导入 joblib，用于加载 compare_models.py 保存的最佳模型。
import joblib

# 导入 Pandas，用于保存预测结果和分类报告。
import pandas as pd

# 导入 classification_report，用于生成每个类别的详细指标。
from sklearn.metrics import classification_report

# 从公共工具模块导入本脚本需要的函数和路径。
from utils import (
    CLASS_NAMES,
    DEFAULT_RANDOM_STATE,
    MODEL_DIR,
    PLOT_DIR,
    RESULT_DIR,
    ensure_directories,
    evaluate_model,
    load_dataset,
    plot_confusion_matrix,
    save_json,
    split_dataset,
)


def parse_args() -> argparse.Namespace:
    """解析命令行参数。"""

    # 创建参数解析器。
    parser = argparse.ArgumentParser(
        description="Evaluate the validation-selected best model on the test set."
    )

    # 添加最佳模型文件路径参数。
    parser.add_argument(
        "--model-path",
        type=Path,
        default=MODEL_DIR / "best_model.joblib",
        help="Path to the best model payload generated by compare_models.py.",
    )

    # 添加随机种子参数；它必须与模型比较阶段保持一致。
    parser.add_argument(
        "--random-state",
        type=int,
        default=DEFAULT_RANDOM_STATE,
        help="Must match the random state used in compare_models.py.",
    )

    # 返回解析后的参数。
    return parser.parse_args()


def main() -> None:
    """加载最佳模型并完成独立测试。"""

    # 解析命令行参数。
    args = parse_args()

    # 创建输出目录。
    ensure_directories()

    # 检查最佳模型文件是否存在。
    if not args.model_path.exists():
        # 如果模型不存在，给出明确提示并终止程序。
        raise FileNotFoundError(
            f"Best model not found: {args.model_path}\n"
            "Run compare_models.py before evaluate_best_model.py."
        )

    # 加载最佳模型载荷。
    payload = joblib.load(args.model_path)

    # 从载荷中取出已经训练好的模型。
    model = payload["model"]

    # 从载荷中取出模型名称。
    model_name = str(payload["model_name"])

    # 检查评估时的随机种子是否与模型选择阶段一致。
    saved_random_state = int(payload["random_state"])

    # 如果随机种子不一致，数据划分会变化，因此直接报错。
    if saved_random_state != args.random_state:
        # 抛出错误，防止用错误的测试集划分评估模型。
        raise ValueError(
            "random_state does not match the value used during model selection. "
            f"Saved={saved_random_state}, current={args.random_state}."
        )

    # 重新加载原始数据集。
    X, y, _ = load_dataset()

    # 使用同一随机种子重建完全相同的数据划分。
    splits = split_dataset(X, y, random_state=args.random_state)

    # 只在这里使用独立测试集评估模型。
    test_metrics, test_predictions, test_scores = evaluate_model(
        model,
        splits["X_test"],
        splits["y_test"],
    )

    # 生成每个类别的 Precision、Recall、F1 和 Support 报告。
    report = classification_report(
        splits["y_test"],
        test_predictions,
        labels=[0, 1],
        target_names=[CLASS_NAMES[0], CLASS_NAMES[1]],
        output_dict=True,
        zero_division=0,
    )

    # 把分类报告转换成 DataFrame。
    report_frame = pd.DataFrame(report).transpose()

    # 保存分类报告为 CSV。
    report_frame.to_csv(
        RESULT_DIR / "test_classification_report.csv",
        encoding="utf-8-sig",
    )

    # 复制测试集特征的索引，便于记录每个样本的预测结果。
    test_indices = splits["X_test"].index

    # 创建逐样本预测结果表。
    predictions_frame = pd.DataFrame(
        {
            "original_index": test_indices,
            "true_label": splits["y_test"].to_numpy(),
            "true_class": [
                CLASS_NAMES[int(label)]
                for label in splits["y_test"].to_numpy()
            ],
            "predicted_label": test_predictions,
            "predicted_class": [
                CLASS_NAMES[int(label)]
                for label in test_predictions
            ],
            "malignant_score": test_scores,
            "is_correct": (
                splits["y_test"].to_numpy() == test_predictions
            ),
        }
    )

    # 保存逐样本预测结果。
    predictions_frame.to_csv(
        RESULT_DIR / "test_predictions.csv",
        index=False,
        encoding="utf-8-sig",
    )

    # 保存测试集总体指标和模型信息。
    save_json(
        {
            "model_name": model_name,
            "random_state": args.random_state,
            "positive_class": "malignant",
            "test_sample_count": int(len(splits["y_test"])),
            "test_metrics": test_metrics,
            "selection_rule": payload.get("selection_rule"),
            "model_set": payload.get("model_set", "unknown"),
        },
        RESULT_DIR / "final_test_metrics.json",
    )

    # 绘制测试集混淆矩阵。
    plot_confusion_matrix(
        splits["y_test"],
        test_predictions,
        f"Test Confusion Matrix - {model_name}",
        PLOT_DIR / "final_test_confusion_matrix.png",
    )

    # 打印分隔线。
    print("=" * 80)

    # 打印标题。
    print("Final Independent Test Evaluation")

    # 打印分隔线。
    print("=" * 80)

    # 打印最佳模型名称。
    print(f"Model: {model_name}")

    # 打印正类含义。
    print("Positive class: malignant = 1")

    # 打印测试集大小。
    print(f"Test samples: {len(splits['y_test'])}")

    # 打印空行。
    print()

    # 依次打印每一项测试指标。
    for metric_name, metric_value in test_metrics.items():
        # 对浮点指标保留四位小数，对计数指标直接打印。
        if isinstance(metric_value, float):
            # 打印浮点指标。
            print(f"{metric_name:<20}: {metric_value:.4f}")
        else:
            # 打印整数计数。
            print(f"{metric_name:<20}: {metric_value}")

    # 打印分类报告标题。
    print("\nClassification report:")

    # 打印分类报告表。
    print(report_frame.to_string(float_format=lambda value: f"{value:.4f}"))

    # 打印输出文件提示。
    print(f"\nMetrics saved to: {RESULT_DIR / 'final_test_metrics.json'}")

    # 打印混淆矩阵图片路径。
    print(f"Confusion matrix saved to: {PLOT_DIR / 'final_test_confusion_matrix.png'}")


# 只有直接运行本文件时才调用 main。
if __name__ == "__main__":
    # 启动最终评估。
    main()
